FROM node:20-alpine

WORKDIR /app

# Copiar archivos de dependencias
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto de los archivos
COPY . .

# Exponer el puerto de Next.js
EXPOSE 3000

# Comando por defecto
CMD ["npm", "run", "dev"]

